import 'package:dio/dio.dart';
import 'package:redbull/models/post_model.dart';

class SearchApi {
  String url = 'https://api.cohora.net/search/v1/search';
  Dio? _dio;

  SearchApi() {
    _dio = Dio();
  }

  Future<List<Profiles>?> fetchProfiles(String query) async {
    try {
      Response response =
          await _dio!.get(url, queryParameters: {'query': query});
      Autogenerated autogenerated = Autogenerated.fromJson(response.data);
      return autogenerated.profiles;
    } on DioError catch (e) {
      print(e.message);
    }
    return null;
  }

  Future<List<Posts>?> fetchPost(String query) async {
    try {
      Response response =
          await _dio!.get(url, queryParameters: {'query': query});
      Autogenerated autogenerated = Autogenerated.fromJson(response.data);
      return autogenerated.posts;
    } on DioError catch (e) {
      print(e.message);
    }
    return null;
  }

  Future<List<SearchComments>?> fetchComments(String query) async {
    try {
      Response response =
          await _dio!.get(url, queryParameters: {'query': query});
      Autogenerated autogenerated = Autogenerated.fromJson(response.data);
      return autogenerated.searchComments;
    } on DioError catch (e) {
      print(e.message);
    }
    return null;
  }
}
